[project]
name = 'erc-8004-stacks-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.identity-registry]
path = 'contracts/identity-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.reputation-registry]
path = 'contracts/reputation-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.validation-registry]
path = 'contracts/validation-registry.clar'
clarity_version = 4
epoch = 'latest'

[repl.analysis]
passes = ['call_checker', 'check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
